config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :backend do
    get 'dashboard', to:'dashboard#index'
    resources :products
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.is_admin?
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      #user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
    end
  end

  def is_admin?
    "admin" == role
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/backend/base_controller.rb
class Backend::BaseController < ApplicationController
  layout 'backend'

  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/backend/dashboard_controller.rb
class Backend::DashboardController < Backend::BaseController
  def index
    authorize! :manage, :all
  end
end

app/controllers/backend/products_controller.rb
class Backend::ProductsController < Backend::BaseController

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to backend_products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
     @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to backend_products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
     if @product.destroy
     redirect_to backend_products_path
     end
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :is_online, :image)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backend/base_helper.rb
module Backend::BaseHelper
end

app/helpers/backend/dashboard_helper.rb
module Backend::DashboardHelper
end

app/helpers/backend/products_helper.rb
module Backend::ProductsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">賺很大商店</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to '更新個人資料', edit_user_registration_path %></li>

              <% if can? :manage, User %>
              <li><%= link_to '後台管理系統', backend_dashboard_path %></li>
              <% end %>

              <li class="divider"></li>
              <li><%= link_to '登出', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to '註冊', new_user_registration_path %></li>
          <li><%= link_to '登入', backend_dashboard_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/application/_navbar_backend.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "商店管理系統", backend_dashboard_path, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "商品管理", backend_products_path %></li>
            <li><%= link_to "新增商品", new_backend_product_path %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to '更新個人資料', edit_user_registration_path %></li>
              <% if can? :manage, User %>
              <li><%= link_to '後台管理系統', backend_dashboard_path %></li>
              <% end %>
              <li class="divider"></li>
              <li><%= link_to '登出', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to '註冊', new_user_registration_path %></li>
          <li><%= link_to '登入', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/backend/dashboard/index.html.erb
<h1>Hi, Ruby</h1>

app/views/backend/products/_form.html.erb
<%= simple_form_for [:backend, @product] do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :is_online %>
  <%= f.input :image %>
  <%= f.submit %>
<% end %>

app/views/backend/products/edit.html.erb
<h1>編輯商品</h1>

<%= render 'form' %>

app/views/backend/products/index.html.erb
<h1>商品列表</h1>

<table class="table table-hover">
 <tr>
   <td>名稱</td>
   <td>價錢</td>
   <td>圖片</td>
   <td>管理按鈕</td>
 </tr>
  <br>
  <% @products.each do |p| %>
  <tr>
    <td><%= p.name %></td>
    <td><%= p.price %></td>
    <td><%= p.image %></td>
    <td><%= link_to '編輯', edit_backend_product_path(p.id), class:'btn btn-success' %>
      <%= link_to '刪除',backend_product_path(p.id), :method => :delete, class:'btn btn-success', data: {confirm: "確定要刪除嗎"} %></td>
  </tr>
  <% end %>
</table>

<%= link_to '新增', new_backend_product_path, class:'btn btn-success' %>

app/views/backend/products/new.html.erb
<h1>新增商品</h1>

<%= render 'form' %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Happy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'navbar' %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Happy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'navbar_backend' %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>